# Generated by Django 2.1.5 on 2020-02-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scraping',
            fields=[
                ('scraping_id', models.AutoField(primary_key=True, serialize=False)),
                ('scraping_heading', models.CharField(max_length=250)),
                ('scraping_body', models.TextField()),
            ],
        ),
    ]
